In [3]:
import pandas as pd
import numpy as np

## Importing data and lookup table

In [4]:
import requests

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet"
response = requests.get(url)

with open("yellow_tripdata_2025-01.parquet", "wb") as f:
    f.write(response.content)

In [5]:
import pandas as pd

df_raw = pd.read_parquet("yellow_tripdata_2025-01.parquet")

df_raw

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.00,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.10,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.00
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.10,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.00
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.20,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.80,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.00,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.00,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.00,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.00,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.00,0.0,1.0,16.09,NaN,NaN,0.00

In [6]:
import requests

url = "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv"
response = requests.get(url)

with open("taxi_zone_lookup.csv", "wb") as f:
    f.write(response.content)

In [7]:
import pandas as pd

taxi_lookup = pd.read_csv("taxi_zone_lookup.csv")
print(taxi_lookup.head())

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

## Creating a copy of raw data

In [8]:
nyc_taxi = df_raw.copy()

In [9]:
nyc_taxi.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [10]:
nyc_taxi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), object(1)
memory usage: 490.5+ MB

## Replacing null values withy appropriate values

In [11]:
nyc_taxi.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          540149
trip_distance                 0
RatecodeID               540149
store_and_fwd_flag       540149
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     540149
Airport_fee              540149
cbd_congestion_fee            0
dtype: int64

In [12]:
nyc_taxi.columns = nyc_taxi.columns.str.lower().str.strip().str.replace(" ", "_")

In [13]:
nyc_taxi['passenger_count'] = nyc_taxi['passenger_count'].fillna(1)
nyc_taxi['ratecodeid'] = nyc_taxi['ratecodeid'].fillna(1)

In [14]:
nyc_taxi['store_and_fwd_flag'] = nyc_taxi['store_and_fwd_flag'].fillna('N')
nyc_taxi['airport_fee'] = nyc_taxi['airport_fee'].fillna(0)
nyc_taxi['congestion_surcharge'] = nyc_taxi['congestion_surcharge'].fillna(0)

## Giving appropriate datatype to columns

In [15]:
nyc_taxi['passenger_count'] = nyc_taxi['passenger_count'].astype(int)

## Creating new useful features and standardising data

In [16]:
nyc_taxi['trip_duration'] = (nyc_taxi['tpep_dropoff_datetime'] - nyc_taxi['tpep_pickup_datetime']).dt.total_seconds() / 60

In [17]:
nyc_taxi['pickup_hour'] = nyc_taxi['tpep_pickup_datetime'].dt.hour

In [18]:
nyc_taxi['pickup_day'] = nyc_taxi['tpep_pickup_datetime'].dt.day_name()

In [19]:
nyc_taxi['speed'] = nyc_taxi['trip_distance'] / (nyc_taxi['trip_duration'] / 60)

In [20]:
nyc_taxi = nyc_taxi[(nyc_taxi['trip_duration'] > 0) & (nyc_taxi['trip_duration'] < 300)]

In [21]:
nyc_taxi = nyc_taxi[(nyc_taxi['trip_distance'] > 0) & (nyc_taxi['trip_distance'] < 100)]

In [22]:
nyc_taxi = nyc_taxi[(nyc_taxi['speed'] > 2) & (nyc_taxi['speed'] < 80)]

In [23]:
nyc_taxi['fare_amount'].quantile([0.99])

0.99    70.2
Name: fare_amount, dtype: float64

In [24]:
nyc_taxi = nyc_taxi[(nyc_taxi['fare_amount'] > 0) & (nyc_taxi['fare_amount'] < 100)]

In [25]:
nyc_taxi = nyc_taxi[(nyc_taxi['passenger_count'] > 0) & (nyc_taxi['passenger_count'] <= 6)]

In [26]:
nyc_taxi = nyc_taxi[(nyc_taxi['total_amount'] > 0)]

## Merging with lookup table

In [38]:
taxi_lookup['Borough'] = taxi_lookup['Borough'].fillna('Unknown')
taxi_lookup['Zone'] = taxi_lookup['Zone'].fillna('Unknown')
taxi_lookup['service_zone'] = taxi_lookup['service_zone'].fillna('Unknown')

In [40]:
nyc_taxi = nyc_taxi.merge(taxi_lookup, left_on='pulocationid', right_on='LocationID', how='left')
nyc_taxi = nyc_taxi.rename(columns={'zone': 'pickup_zone', 'borough': 'pickup_borough'})

nyc_taxi = nyc_taxi.merge(taxi_lookup, left_on='dolocationid', right_on='LocationID', how='left')
nyc_taxi = nyc_taxi.rename(columns={'zone': 'dropoff_zone', 'borough': 'dropoff_borough'})

In [41]:
nyc_taxi.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,...,pickup_day,speed,LocationID_x,Borough_x,Zone_x,service_zone_x,LocationID_y,Borough_y,Zone_y,service_zone_y
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1,1.60,1.0,N,229,237,1,...,Wednesday,11.497006,229,Manhattan,Sutton Place/Turtle Bay North,Yellow Zone,237,Manhattan,Upper East Side South,Yellow Zone
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1,0.50,1.0,N,236,237,1,...,Wednesday,11.764706,236,Manhattan,Upper East Side North,Yellow Zone,237,Manhattan,Upper East Side South,Yellow Zone
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1,0.60,1.0,N,141,141,1,...,Wednesday,18.461538,141,Manhattan,Lenox Hill West,Yellow Zone,141,Manhattan,Lenox Hill West,Yellow Zone
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3,0.52,1.0,N,244,244,2,...,Wednesday,5.604790,244,Manhattan,Washington Heights South,Boro Zone,244,Manhattan,Washington Heights South,Boro Zone
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3,0.66,1.0,N,244,116,2,...,Wednesday,11.207547,244,Manhattan,Washington Heights South,Boro Zone,116,Manhattan,Hamilton Heights,Boro Zone

In [64]:
nyc_taxi['trip_duration'].head()

0    8.350000
1    2.550000
2    1.950000
3    5.566667
4    3.533333
Name: trip_duration, dtype: float64

In [46]:
nyc_taxi.isnull().sum()

# nyc_taxi['Borough_x'].isnull().sum()

vendorid                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
ratecodeid               0
store_and_fwd_flag       0
pulocationid             0
dolocationid             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
airport_fee              0
cbd_congestion_fee       0
trip_duration            0
pickup_hour              0
pickup_day               0
speed                    0
LocationID_x             0
Borough_x                0
Zone_x                   0
service_zone_x           0
LocationID_y             0
Borough_y                0
Zone_y                   0
service_zone_y           0
dtype: int64

In [47]:
nyc_taxi.shape

(3202772, 32)

In [48]:
nyc_taxi.to_csv("cleaned_nyc_taxi.csv", index=False)